services:

  mysql:
    image: mysql:8.0
    container_name: oliveseeds-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mystore
      MYSQL_ROOT_PASSWORD: Christ7ak5oss
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mystore.sql:/docker-entrypoint-initdb.d/mystore.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pCoss"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: oliveseeds-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Christ7ak5oss
      DB_NAME: mystore
      PORT: 5000
      JWT_SECRET: OliveSeeds_2026_SuperSecret_ChangeOSS
    depends_on:
      - mysql


  public-website:
    build:
      context: ./public-website
    container_name: oliveseeds-public
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend


  admin-panel:
    build:
      context: ./admin-panel
    container_name: oliveseeds-admin
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  mysql_data:
